apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: j9q403gl2-python
  janus-idp.io/tekton: j9q403gl2-python
  backstage.io/kubernetes-id: j9q403gl2-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: j9q403gl2-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
